#.travis.yml

language: node_js
node_js:
  - "9.5"

branches:
  only:
    - develop

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod
  - cd ./functions && npm install

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change